// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwX0AIZxTWVseHo-iyKgXiV03VgBZ5Mwo',
    appId: '1:148020391959:web:c9622f712a81adeb00ac52',
    messagingSenderId: '148020391959',
    projectId: 'order-management-system-c44e2',
    authDomain: 'order-management-system-c44e2.firebaseapp.com',
    storageBucket: 'order-management-system-c44e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5kx6AXlISpZX68T5KlVgT7Dl2h942-k',
    appId: '1:148020391959:android:62cbc8912de2641e00ac52',
    messagingSenderId: '148020391959',
    projectId: 'order-management-system-c44e2',
    storageBucket: 'order-management-system-c44e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8NJdicQzWJgRnzqFkF0ntn0M7UnFHRcg',
    appId: '1:148020391959:ios:3d3a8578ec27f79700ac52',
    messagingSenderId: '148020391959',
    projectId: 'order-management-system-c44e2',
    storageBucket: 'order-management-system-c44e2.appspot.com',
    androidClientId:
        '148020391959-0ttbq5568d5cq5potl20nq7p74brvjof.apps.googleusercontent.com',
    iosClientId:
        '148020391959-eh0igsce9fldb7vkjoepsi7cmf3k49dj.apps.googleusercontent.com',
    iosBundleId: 'com.example.oms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8NJdicQzWJgRnzqFkF0ntn0M7UnFHRcg',
    appId: '1:148020391959:ios:0c7b83168aed040400ac52',
    messagingSenderId: '148020391959',
    projectId: 'order-management-system-c44e2',
    storageBucket: 'order-management-system-c44e2.appspot.com',
    androidClientId:
        '148020391959-0ttbq5568d5cq5potl20nq7p74brvjof.apps.googleusercontent.com',
    iosClientId:
        '148020391959-k6ht9gn8aqu46gfm7j3vt3aok99fhk02.apps.googleusercontent.com',
    iosBundleId: 'com.example.oms.RunnerTests',
  );
}
